from __future__ import annotations
from typing import List, Optional, Protocol, runtime_checkable

from .schema import Record, Slot


@runtime_checkable
class StoreProtocol(Protocol):
    """Minimal interface that any backing store must satisfy."""

    def append(self, rec: Record) -> None: ...
    def get(self, rec_id: str) -> Optional[Record]: ...
    def list_slot(self, slot: Slot) -> List[Record]: ...
    def find_active_by_kind(self, slot: Slot, kind: str, trace_id: str) -> Optional[Record]: ...
    def invalidate(self, rec_id: str, reason: str) -> None: ...
    def close(self) -> None: ...
